name: Run-Benchmarks
run-name: ${{ gitea.actor }} Running Benchmarking Actions
on:
  workflow_run:
    workflows: [Run-Tests]
    types:
      - completed

jobs:
  Benchmark:
    runs-on: arm-locked-freq-linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Build
        run: cmake --build --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Run Benchmarks
        run: ./benchmark/infrastructure/infrastructure_benchmark --benchmark_out=${{ gitea.sha }}_${{ gitea.run_number }}.json --benchmark_out_format=json
        working-directory: ${{ gitea.workspace }}-build-linux-default-release

      - name: Compare Benchmarks
        run: python3 compare.py ${{ gitea.workspace }}-build-linux-default-release/${{ gitea.sha }}_${{ gitea.run_number }}.json
        working-directory: ${{ gitea.workspace }}/.gitea/workflows/
