name: Run Tests and Benchmarks
run-name: ${{ gitea.actor }} Running Tests and Benchmarks Actions
on: [push]

jobs:
  Tests:
    runs-on: arm-locked-freq-linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Build
        run: cmake --build --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Run Tests
        run: ./test/infrastructure/infrastructure_test
        working-directory: ${{ gitea.workspace }}-build-linux-default-release

  Benchmarks:
    needs: Tests
    runs-on: arm-locked-freq-linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Build
        run: cmake --build --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Cache Warm-Up
        run: ./benchmark/infrastructure/infrastructure_benchmark
        working-directory: ${{ gitea.workspace }}-build-linux-default-release

      - name: Run Benchmarks
        run: ./benchmark/infrastructure/infrastructure_benchmark --benchmark_out=${{ gitea.sha }}_${{ gitea.run_number }}.json --benchmark_out_format=json
        working-directory: ${{ gitea.workspace }}-build-linux-default-release

      - name: Compare Benchmarks
        run: python3 compare.py ${{ gitea.workspace }}-build-linux-default-release/${{ gitea.sha }}_${{ gitea.run_number }}.json
        working-directory: ${{ gitea.workspace }}/.gitea/workflows/
