name: Run-Tests
run-name: ${{ gitea.actor }} Running Tests Actions
on: [push]

jobs:
  Benchmark:
    runs-on: arm-locked-freq-linux

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Build
        run: cmake --build --preset linux-default-release
        working-directory: ${{ gitea.workspace }}

      - name: Run Tests
        run: ./test/infrastructure/infrastructure_test
        working-directory: ${{ gitea.workspace }}-build-linux-default-release
